BOARD_SIZE = 8
SQUARE_SIZE = 80

LIGHT_COLOR = "#F0D9B5"
DARK_COLOR = "#B58863"

SIDE_PANEL_WIDTH = 350

WINDOW_WIDTH = (BOARD_SIZE * SQUARE_SIZE) + SIDE_PANEL_WIDTH
WINDOW_HEIGHT = BOARD_SIZE * SQUARE_SIZE